apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt-vm: vm-{{.name}}-{{.Replica}}
    test-type: memory-limits
    {{- range $key, $value := .vmLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  name: {{.name}}-{{.Replica}}
spec:
  runStrategy: {{ if .VMIrunning }}Always{{ else }}Halted{{ end }}
  template:
    metadata:
      labels:
        kubevirt-vm: vm-{{.name}}-{{.Replica}}
        kubevirt.io/os: {{.OS}}
        test-type: memory-limits
        {{- range $key, $value := .vmLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            noCloud: {}
          source:
            secret:
              secretName: "{{ .sshPublicKeySecret }}-{{ .counter }}"
      {{- if .nodeSelector }}
      nodeSelector:
        {{ .nodeSelector }}
      {{- end }}
      domain:
        cpu:
          cores: {{.cpuCores}}
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        resources:
          requests:
            memory: {{.memory}}
          # Add memory overcommit for large memory tests
          {{- $memoryBytes := .memory | regexReplaceAll "[^0-9]" "" | int }}
          {{- if gt $memoryBytes 100 }}
          limits:
            memory: {{.memory}}
          {{- end }}
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: dvclone-{{.Replica}}
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... # Add your SSH key here
            runcmd:
              # Install memory testing tools
              - dnf install -y stress-ng htop free
              # Calculate memory to stress (90% of available)
              - TOTAL_MEM=$(free -m | awk 'NR==2{printf "%.0f", $2*0.9}')
              # Start memory stress test
              - nohup stress-ng --vm 4 --vm-bytes ${TOTAL_MEM}M --vm-method all --verify --timeout 0 &
        name: cloudinitdisk
  dataVolumeTemplates:
  - metadata:
      name: dvclone-{{.Replica}}
    spec:
      source:
            http:
                url: "https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2"
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{.storage}}
        storageClassName: {{.storageclass}}
        volumeMode: {{.volumemode}}