apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: {{ .udnName }}
spec:
  topology: Layer2
  layer2:
    role: Primary
    subnets:
      - "{{ .udnSubnet }}"
    ipam:
      lifecycle: Persistent
