{{- $PROM := .PROM -}}
{{- $PROM_TOKEN := .PROM_TOKEN -}}
{{- $kubeBurnerFQDN := "kube-burner.io" -}}
{{- $testName := "cnv-cpu-limits" }}
{{- $nsName := .testNamespace | default "cnv-cpu-limits" -}}
{{- $vmCount := .vmCount | default 1 -}}
{{- $vmName := "cpu-test-vm" -}}
{{- $sshPublicKeySecretName := $vmName -}}
{{- $jobCounterLabelKey := (list $testName "." $kubeBurnerFQDN "/counter") | join "" -}}
{{- $jobCounterLabelValue := (list "counter-" (.counter | toString )) | join "" -}}
{{- $testNamespacesLabelKey := (list $kubeBurnerFQDN "/test-name") | join "" -}}
{{- $testNamespacesLabelValue := $testName -}}
{{- $metricsBaseDirectory := $testName -}}
---
global:
  measurements:
  - name: vmiLatency
  - name: pvcLatency

metricsEndpoints:
- indexer:
    type: local
    metricsDirectory: "{{ .resultsPath }}/{{ .runTimestamp }}/iteration-{{ .counter | toString }}"
{{- if .esServer }}
- endpoint: {{ .PROM }}
  token: {{ .PROM_TOKEN }}
  metrics: [../../config/metrics-profiles/kubevirt-metrics.yaml]
  indexer:
    type: elastic
    defaultIndex: {{ .testName }}
    esServers: [{{ .esServer }}]
    insecureSkipVerify: true
{{- end }}

jobs:
# Run cleanup only when counter is 0
{{ if eq (.counter | int) 0 }}
- name: start-fresh
  jobType: delete
  waitForDeletion: true
  qps: 5
  burst: 10
  objects:
  - kind: Namespace
    labelSelector:
      {{ $testNamespacesLabelKey }}: {{ $testNamespacesLabelValue }}
{{ end }}

- name: cpu-limits-test
  jobType: create
  jobIterations: 1
  qps: 5
  burst: 10
  namespacedIterations: false
  namespace: {{ $nsName }}
  namespaceLabels:
    {{ $testNamespacesLabelKey }}: {{ $testNamespacesLabelValue }}
  # verify object count after running each job
  verifyObjects: true
  errorOnVerify: true
  # interval between jobs execution
  jobIterationDelay: 20s
  # wait all VMI be in the Ready Condition
  waitWhenFinished: false
  podWait: true
  maxWaitTimeout: {{ .maxWaitTimeout | default "30m" }}
  jobPause: {{ .jobPause | default "2m" }}
  cleanup: false
  # Set missing key as empty to allow using default values
  defaultMissingKeysWithZero: true
  beforeCleanup: '../../config/scripts/wrapper.sh check_cpu_limits {{ $jobCounterLabelKey }} {{ $jobCounterLabelValue }} {{ $nsName }} {{ .cpuCores | default 1 }} {{ .cpuSockets | default 1 }} {{ .privateKey }} {{ .vmUser }} {{ .guestOS | default "linux" }} {{ .resultsPath }}/{{ .runTimestamp }}/iteration-{{ .counter }}'
  objects:
  - objectTemplate: templates/secret_ssh_public.yml
    runOnce: true
    replicas: 1
    inputVars:
      name: {{ $sshPublicKeySecretName }}
      counter: {{ .counter | toString }}
      publicKey: {{ .publicKey }}
{{- if eq (.guestOS | default "linux") "windows" }}
  - objectTemplate: vm-cpu-windows-template.yml
    replicas: {{ $vmCount }}
    waitOptions:
      labelSelector:
        {{ $jobCounterLabelKey }}: {{ $jobCounterLabelValue }}
    inputVars:
      name: {{ $vmName }}
      counter: {{ .counter | toString }}
      OS: windows
      registryUrl: "{{ .windowsImageUrl }}"
      cpuCores: {{ .cpuCores | default 1 }}
      cpuSockets: {{ .cpuSockets | default 1 }}
      memory: {{ .memory | default "2Gi" }}
      storage: {{ .windowsRootDiskSize | default "100Gi" }}
      storageclass: {{ .storageClassName | default "ocs-storagecluster-ceph-rbd" }}
      volumemode: {{ .volumeMode | default "Block" }}
      VMIrunning: {{ .vmRunning | default true }}
      nodeSelector: {{ .nodeSelector | default "" }}
      vmUser: {{ .vmUser | default "Administrator" }}
      sshPublicKeySecret: {{ $sshPublicKeySecretName }}
      vmLabels:
        {{ $jobCounterLabelKey }}: {{ $jobCounterLabelValue }}
{{- else }}
  - objectTemplate: vm-cpu-template.yml
    replicas: {{ $vmCount }}
    waitOptions:
      labelSelector:
        {{ $jobCounterLabelKey }}: {{ $jobCounterLabelValue }}
    inputVars:
      name: {{ $vmName }}
      counter: {{ .counter | toString }}
      OS: fedora
      url: {{ .imageUrl | default "https://dl.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2" }}
      cpuCores: {{ .cpuCores | default 1 }}
      cpuSockets: {{ .cpuSockets | default 1 }}
      cpuMaxSockets: {{ .cpuMaxSockets | default 1 }}
      bootloaderEfi: {{ .bootloaderEfi | default false }}
      memory: {{ .memory | default "2Gi" }}
      storage: {{ .storage | default "10Gi" }}
      storageclass: {{ .storageClassName | default "ocs-storagecluster-ceph-rbd" }}
      volumemode: {{ .volumeMode | default "Block" }}
      VMIrunning: {{ .vmRunning | default true }}
      nodeSelector: {{ .nodeSelector | default "" }}
      sshPublicKeySecret: {{ $sshPublicKeySecretName }}
      publicKey: {{ .publicKey }}
      vmLabels:
        {{ $jobCounterLabelKey }}: {{ $jobCounterLabelValue }}
{{- end }}