apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt-vm: vm-{{.name}}-{{.Replica}}
    test-type: cpu-limits
{{- range $key, $value := .vmLabels }}
    {{ $key }}: {{ $value }}
{{- end }}
  name: {{.name}}-{{.Replica}}
spec:
  runStrategy: {{ if .VMIrunning }}Always{{ else }}Halted{{ end }}
  template:
    metadata:
      labels:
        kubevirt-vm: vm-{{.name}}-{{.Replica}}
        kubevirt.io/os: {{.OS}}
        test-type: cpu-limits
{{- range $key, $value := .vmLabels }}
        {{ $key }}: {{ $value }}
{{- end }}
    spec:
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            noCloud: {}
          source:
            secret:
              secretName: "{{ .sshPublicKeySecret }}-{{ .counter }}"
      {{- if .nodeSelector }}
      nodeSelector:
        {{ .nodeSelector }}
      {{- end }}
      domain:
        cpu:
          cores: {{.cpuCores}}
          # Enable CPU pinning for high CPU count tests
          {{- if gt (.cpuCores | int) 16 }}
          dedicatedCpuPlacement: true
          {{- end }}
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        resources:
          requests:
            memory: {{.memory}}
            {{- if gt (.cpuCores | int) 16 }}
            cpu: {{.cpuCores}}
            {{- end }}
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: dvclone-{{.Replica}}
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... # Add your SSH key here
            runcmd:
              # Install stress-ng for CPU testing
              - dnf install -y stress-ng htop
              # Start CPU stress test matching the number of cores
              - nohup stress-ng --cpu {{.cpuCores}} --timeout 0 &
        name: cloudinitdisk
  dataVolumeTemplates:
  - metadata:
      name: dvclone-{{.Replica}}
    spec:
      source:
            http:
                url: "https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2"
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{.storage}}
        storageClassName: {{.storageclass}}
        volumeMode: {{.volumemode}}