apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  labels:
    test-type: per-host-density
  name: {{.name}}
spec:
  source:
{{- if hasPrefix "docker://" .imageUrl }}
    registry:
      url: {{ .imageUrl }}
{{- else if hasPrefix "pvc://" .imageUrl }}
{{- $pvcParts := splitList "/" (trimPrefix "pvc://" .imageUrl) }}
    pvc:
      namespace: {{ index $pvcParts 0 }}
      name: {{ index $pvcParts 1 }}
{{- else }}
    http:
        url: {{.imageUrl}}
{{- end }}
  storage:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{.storage}}
    storageClassName: {{.storageclass}}
    volumeMode: {{.volumemode}}